GET http://localhost:8000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NTY0MzIxLCJpYXQiOjE3Mzc1NjQwMjEsImp0aSI6ImJhNmYyMDlmNGQ3OTRjMTNiOGYwZTBlOWIyOTQyYWViIiwidXNlcl9pZCI6MTN9.P9Og2yNVV0maudVj0W6Ov7Cod3WPBH7onixIGOswEN4