version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./Database:/var/lib/postgresql/data/

  backend:
    build: ./Backend
    env_file:
      - ./.env
    volumes:
      - ./Backend:/usr/src/app/
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
      - redis

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/var/www/html
    expose:
      - 9000
    depends_on:
      - db
      - backend

  server:
    ports:
      - 443:443
    expose:
      - 443
    build: ./Server
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:5
    restart: always
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    env_file:
      - ./.env
    volumes:
      - ./Alertmanager/config:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    env_file:
      - ./.env
    volumes:
      - ./Grafana/dashboards:/var/lib/grafana/dashboards
      - ./Grafana/provisioning:/etc/grafana/provisioning:ro
    restart: always

  blockchain:
    build: ./Contracts
    volumes:
      - ./Contracts:/usr/src/contracts
    env_file:
      - ./.env
