version: '3.8'

services:

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - pgdata:/var/lib/postgresql/data/ 

  frontend:
      build: ./Frontend
      volumes:
        - ./Frontend:/var/www/html
      ports:
        - 443:443
      depends_on:
        - db
        - backend
 
volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /home/jorteixe/ft_transcendence/Database
      o: bind