version: '3.8'

services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_prod
    env_file:
      - ./.env.prod.db

  server:
    image: nginx
    ports:
      - 443:443
    expose:
      - 443
    build: ./Server
    restart: on-failure
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /home/masoares/ft_transcendence/Database/
      o: bind