version: '3.8'

services:
  backend:
    build: ./Backend
    volumes:
      - ./Backend:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/var/www/html
    ports:
      - 443:443
    depends_on:
      - db
      - backend
  
  redis:
    image: redis:5
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/ft_transcendence/Database
      o: bind