version: '3.8'

services:

  db:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

  backend:
    build: ./Backend 
    env_file:
      - ./.env
    volumes:
      - ./Backend:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis


  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - db
      - backend
  
  server:
    ports:
      - 443:443
    expose:
      - 443
    build: ./Server
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:5
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/ft_transcendence/Database
      o: bind