# Generated by Django 5.1.4 on 2025-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_siteuser_groups_siteuser_is_active_siteuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='nickname',
        ),
    ]
