# Generated by Django 5.1.4 on 2025-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_URL',
            field=models.URLField(default='https://www.shutterstock.com/image-vector/funny-art-borat-illustration-glasses-600nw-2157502681.jpg'),
        ),
    ]
