# Generated by Django 5.1.4 on 2025-01-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_siteuser_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='online_status',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='token',
        ),
    ]
