# Generated by Django 5.1.4 on 2025-01-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_siteuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_staff',
        ),
    ]
