# Generated by Django 5.1.4 on 2025-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_siteuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
