# Generated by Django 5.1.4 on 2025-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_siteuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
