# Generated by Django 5.1.4 on 2025-01-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_siteuser_is_active_siteuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='profile_image',
        ),
    ]
