# Generated by Django 5.1.4 on 2025-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_siteuser_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
