# Generated by Django 5.1.4 on 2025-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_siteuser_two_fa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
