# Generated by Django 5.1.4 on 2025-02-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_siteuser_is_otp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ball_color', models.CharField(max_length=7)),
                ('background_color', models.CharField(max_length=7)),
                ('paddle_color', models.CharField(max_length=7)),
                ('wall_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='selected_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gamemap'),
        ),
    ]
