# Generated by Django 5.1.4 on 2025-02-06 13:13

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_gamemap_siteuser_selected_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='selected_map',
            field=models.ForeignKey(default=users.models.GameMap.get_default_map, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gamemap'),
        ),
    ]
