# Generated by Django 5.1.4 on 2025-02-06 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_siteuser_selected_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemap',
            name='background_color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Enter valid hex color')]),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='ball_color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Enter valid hex color')]),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='paddle_color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Enter valid hex color')]),
        ),
        migrations.AlterField(
            model_name='gamemap',
            name='wall_color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Enter valid hex color')]),
        ),
    ]
