# Generated by Django 5.1.4 on 2025-02-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_gamemap_background_color_and_more'),
        ('users', '0019_siteuser_otp_recover_secret'),
    ]

    operations = [
    ]
