# Generated by Django 5.1.4 on 2025-02-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_siteuser_selected_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='selected_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.gamemap'),
        ),
    ]
