# Generated by Django 5.1.4 on 2025-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_siteuser_selected_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='selected_map',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='GameMap',
        ),
    ]
