# Generated by Django 5.1.4 on 2025-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_siteuser_selected_map_delete_gamemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_42user',
            field=models.BooleanField(default=False),
        ),
    ]
